### ISSUE TITLE
MongoDB에서 찾은 다큐멘트 return시 에러발생

### ISSUE THREAD

**Issue by ssooda** [TeamOffPublic/OffOff#11]
client에서 보내는 http method : 회원가입(POST), 로그인(POST), 로그인 시 얻은 토큰으로 회원정보 요청 (GET)

회원정보 요청(GET)시에는 MongoDB에서 다큐멘트를 찾아, 
다큐멘트에 실린 데이터를 반환(return)해주어야합니다.
이 return단계에서 오류가 발생합니다. : json serializable 오류

mongodb에 저장되는 데이터 형식은 BSON이지만, 
데이터를 쿼리하면 JSON 형식을 얻게됩니다. (따라서 별도의 변환이 필요 없습니다.)

하지만 _id 문제(ObjectId), byte자료형 문제, int, too many values to unpack 등 TypeError가 굉장히 다양하게 발생하고 있습니다.

del[_id]->post.py방식, jsonify, json.dumps 등을 사용했으나 아직 에러를 해결하지 못했습니다.

해결방법을 더 찾아봐야 할 것 같습니다.

+ 이 에러는 GET method를 사용하는 모든 경우에  발생할 것 같습니다

**Comment by dlskawns96** [comment]
http로 보내는 모든 GET에 대해 return시 에러가 발생하나요??

**Comment by ssooda** [comment]
아! 방금 해결했습니다!!

제가 만든 파일에서 _id만 문제가 된다고 생각해서 _id만 제거했었는데,
password도 문제가 되더라구요
password도 빼고 데이터를 불러오니까 해결됐습니다!

--------
유민님께서 만들어 놓으셨던 post.py에서는 에러가 발생 안 해요..!
board2.py는 확인해봐야할 것 같아요!

**Comment by dlskawns96** [comment]
👍 👍
