### ISSUE TITLE
회원가입 요청에 대한 응답 오류

### ISSUE THREAD

**Issue by yuuuzzzin** [TeamOffPublic/OffOff#23]
# 문제
회원가입 요청을 보내면 정상적인 응답이 돌아오지 않습니다.

## API 명세서에 적힌 응답 결과
![image](https://user-images.githubusercontent.com/57751515/128802390-adc2d2a7-3c94-4cd1-814f-85f7359837c1.png)

## 안드로이드에서 보내는 객체 형태:
```
User(id=tist12, password=Test123!, info=Info(name=박유진, email=ui1184@test.com, birth=2002년 01월 01일, type=null), subInfo=SubInfo(nickname=윰쥰, profile=null), activity=Activity(posts=null, comments=null, likes=null, bookmarks=null))
```
## 안드로이드에서 받는 응답 결과
status code: 500

이러한 이유로 회원가입 처리에 문제가 있습니다..!

**Comment by ssooda** [comment]
이 문제로 밤새 고민했을 유진 님에게 사과의 말씀을 드립니당,,,😭😭

확인해본 결과 2 가지 문제가 있었습니다.
1. PyJWT와 jwt 간 충돌문제
jwt의 encode 기능이 없다는 오류 메시지를 확인하였고,
jwt 삭제, PyJWT 재설치를 통해 해결할 수 있었습니다.

2. 서버와 로컬 간 PyJWT 버전 차이
PyJWT 버전에 따라 토큰의 타입이 다르다는 것을 알게 되었습니다
토큰이 byte 타입으로 주어지는 경우,
string 타입으로 바꾸는 코드를 추가하였습니다.


수정된 파일을 서버에 업로드 하였고
POSTMAN 테스트 결과 회원가입이 성공적으로 이루어졌습니다  !

클라이언트 쪽에서도 테스트 부탁드립니다!
혹시 다른 문제가 발생하면 언제든지 말씀해주세요 !

우리팀 최고 ~~👍👍👍

**Comment by yuuuzzzin** [comment]
소연 님 너무 너무 수고 많았습니다 ㅠㅠㅠ
회원가입 동작 지금 문제 없이 아주 잘 됩니다 !!
빠른 수정 감사합니다~~~👍
