### ISSUE TITLE
게시글, 댓글, 대댓글 좋아요 기능 구현

### ISSUE THREAD

**Issue by ssooda** [TeamOffPublic/OffOff#30]
# 댓글API 구현 중 생긴 의문

1. 회원의 "activity" 중 "likes"는 좋아요를 누른 **게시글**정보만 저장하나요? 좋아요를 누른 **댓글, 대댓글**에 대한 정보도 저장하나요? 
- 댓글, 대댓글 likes 도 활동 정보에 저장하나요?
- 저장하면 likes 에 같이 저장하나요?
- 아니면 또 다른 Key가 필요한가요?

2. 사용자가 게시글에 좋아요를 누른 경우 채워진 하트❤️는 프론트에서 기억을 하는 건가요? (어플을 나갔다가 들어와도 해당 게시글에서 채워진 하트 ❤️가 유지되는 건 프론트에서 기억하는 건가요?)

# 참고

## 회원 활동 정보 JSON
회원 가입 시 JSON에는 "activity"와 관련하여 
"posts", "likes", "reports", "replies"가 있습니다.
- "posts"는 작성한 게시글
- "reports"는 신고한 게시글
- "replies"는 댓글, 대댓글을 작성한 게시글 정보를 저장합니다.  

## 백앤드에서 회원활동정보 저장
현재 백앤드에서 회원활동 별로 저장하는 data는 다음과 같습니다.

|활동 내용|  활동 저장 정보|
|------------|---------------------|
|게시글 작성| 게시판 이름, 게시글 _id|
|댓글 작성| 게시판 이름, 게시글 _id, 댓글 _id|
|대댓글 작성| 게시판 이름, 게시글 _id, 댓글 _id, 대댓글인지여부(True)|
|게시글 좋아요| 게시판 이름, 게시글 _id|
|댓글/ 대댓글 좋아요(미정)| 게시판 이름, 게시글 _id, 댓글 _id|

~~대댓글 작성과 대댓글 좋아요가 다른 이유 :  회원탈퇴 시 '좋아요'의 경우 별 다른 처리를 할 필요가 없으나, 대댓글 작성의 경우  author의 정보를 None(null) 으로 수정해야하기 때문입니다~~

## 회원활동정보 요청 시 백앤드가 보내주는 정보

여타 커뮤니티 어플에서  
회원활동을 조회하면,

|활동 내용| 활동 조회 시|
|------------|---------------------|
|게시글 작성| 해당 게시글을 보여줌|
|댓글 작성| 해당 댓글의 ***게시글***을 보여줌|
|게시글 좋아요| 해당 게시글을 보여줌|
|댓글/ 대댓글 좋아요(미정)| 해당 댓글/대댓글의 ***게시글***을 보여줌|

이러한 방식으로 회원활동 정보를 조회하게 됩니다.  

따라서 대댓글 좋아요의 경우
백앤드에서는 (현재 db 구조 상)  
해당 유저가 정확히 어떠한 대댓글을 좋아요 눌렀는지 기억할 수 없습니다.

#### *의문 2️⃣ : 그렇다면 채워진 하트❤️는 프론트에서 따로 기억할 수 있나요?*  
  
  
  
# 항상 파이팅입니다 😊😊

**Comment by ssooda** [comment]
다른 커뮤니티 어플은
1. 내가 쓴 글
2.  댓글 단 글
3. 스크랩
이렇게 보여주네용

**Comment by YouminYoumin** [comment]
스크랩 기능은 현재 구현이 되어있지 않으니 고려 대상은 아닐 것 같고, 하트같은 경우는 프론트에서 기억을 하되 백엔드 쪽에서 이 게시글이 현재 사용자가 좋아요를 누른 게시글인지 체크해서 보내주면 되지 않을까싶습니다.

또한 likes의 경우 게시판 정보만 저장해주면 되지 않을까 싶은게 보통 커뮤니티 보면 자신이 좋아요한 게시글은 보여주지만 댓글까지는 보여주진 않는 것 같아서 게시글만 저장하면 될 것 같습니다.

**Comment by ssooda** [comment]
## 기능 정리
1. 게시글, 댓글, 대댓글 좋아요 취소 기능 x
2. 좋아요 누른 경우 채워진 하트 기능 x
3. 게시글에 좋아요 누른 user id를 저장해놓고,   좋아요 신청이왔을 때 Ture(좋아요 가능), False(이미 좋아요 한 경우) 반환


## db 구조
1.  게시글  컬랙션에 저장되는 정보
-likes한 사람
-report한 사람
-bookmark한 사람
-views (횟수)
-replies (횟수)


2. 댓글/대댓글 통합 컬랙션에 저장되는 정보
-likes한 사람


+ 댓글 작성할 때 게시글 repliescount +1 해주기
+ 삭제하면 repliescount -1 해주기


예시)
free_board_reply 컬랙션
{
_id
author
content
date
postId
parentCommentId
likesUsers
}


3. 유저 활동
-likes한 게시글 : 아이디, 게시판
-report한 게시글  아이디, 게시판
-reply한 게시글 아이디, 게시판
-bookmark한 게시글 아이디, 게시판
-Post한 게시글 아이디, 게시판

## JSON
게시글/댓글/대댓글  작성,수정, 삭제에는 author O user O
좋아요 활동에는 authorX  user O
