### ISSUE TITLE
postList, post 조회 시 response 객체에 replyCount 값이 실제 댓글 갯수와 일치하지 않는 버그

### ISSUE THREAD

**Issue by dlskawns96** [TeamOffPublic/OffOff#37]
# 내용 
서버로부터 받아온 데이터로 게시글 목록을 표시하는데, 
서버가 보내주는 postList 객체 안에 post 객체들이 가지고 있는 replyCount가 실제 해당 게시글의 댓글 갯수와 동일하지 않은 버그가 있습니다.

![스크린샷 2021-10-19 오전 11 45 20](https://user-images.githubusercontent.com/22260098/137835155-b7ac83c9-d5c2-412b-8b07-f8e2b8a9ecd9.png)
-> postList를 받아서 한 post를 표시한 이미지, 댓글 => 11개

![image](https://user-images.githubusercontent.com/22260098/137835358-76f290dd-3b8f-4622-a257-774d312268a9.png)
-> 자유 게시판 postList 조회 , 댓글 => 11개
![스크린샷 2021-10-19 오전 11 50 58](https://user-images.githubusercontent.com/22260098/137835674-b1222845-b020-45f8-b2d4-0eee6d0f4505.png)
-> 해당 글 post 조회, 댓글 => 11개

![스크린샷 2021-10-19 오전 11 48 23](https://user-images.githubusercontent.com/22260098/137835409-f8bb681f-ea39-4b10-9789-505237010e4b.png)

-> 실제: 댓글이 짤려서 안보이지만 replies를 서버로 받아왔을 때는 7개

# 요약
postList, post 조회 시 response 객체에 replyCount 값이 부정확합니다.

**Comment by ssooda** [comment]
어제 댓글/대댓글 분리하면서 자유게시판 댓글 컬랙션을 drop해서 발생한 문제인 것 같습니다!
지금까지 작업한 게 아깝지만😭😭 자유게시판 게시글, 댓글 컬랙션 모두 초기화시켰어요!!
또 이런 문제가 발생하면 알려주세요!🙏🙏
