### ISSUE TITLE
게시판 글 목록 불러오기

### ISSUE THREAD

**Issue by ssooda** [TeamOffPublic/OffOff#8]
방식1. (board.py)
클라이언트에서 page 체크해서 넘겨주는 방식
skip, limit 함수 사용

방식2 (board2.py)
클라이언트에서 마지막 게시글의 _id를 체크해서 넘겨주는 방식
skip함수 사용x
limit 함수 사용

방식1의 경우 해당 게시판(collection)의 데이터(document)를 전부 빌드업한 후에 skip하는 방식이라서 느리다는 단점이 있습니다
방식2의 경우 직전 _id보다 더 작은(과거의) 데이터들만 불러오기 때문에 시간은 더 단축된다고 합니다

몽고 db의 _id에 유닉스 시간 정보가 담겨있고, 단순 string이 아니기 때문에 비교연산자를 사용할 수 있어서
방식2를 사용하면 좋을 것 같습니다 !

방식1은 미완성 상태이고 방식2는 완성해뒀습니다. 
확인부탁드려요!

**Comment by dlskawns96** [comment]
방식2를 사용했을 때 [1, 2, 3, 4, 5]번 글이 있고, 5번글이 삭제가 되고 [1, 2, 3, 4] 번 글이 있으면...
그 다음에 있어야 보내줘야 할 6, 7, 8, ... 번 글들이 어차피 마지막 글인 5번 글보다 시점이 느리기 때문에 중간에 삭제된 글도 문제 없이 처리가 잘 될 것 같고, 한번에 보내는 양이 적기 때문에 속도 측면에서 장점도 있을 것 같네요.
방식2로 구현하고 테스트하면 될 것 같습니다.
좋은 이슈 👍 👍 👍

**Comment by yuuuzzzin** [comment]
오오 방식 2는 방식 1처럼 전부 빌드업하지 않아도 되고, 
id 값만 비교해서 데이터를 가져오면 되니까 말씀하신 것처럼 더 효율적일 것 같아요 !!
멋져요!! 🏆🥇

**Comment by ssooda** [comment]
오호 중간에 삭제 되는 건 생각 못했었는데 그 부분도 방식2가 더 좋은 것 같아요!!! 잘 보완해보겠습니다아아!!!!😊
